const axios = require("axios");

const options = {
  method: "POST",
  url: "https://student-result-api.p.rapidapi.com/api/add-student-info",
  headers: {
    "content-type": "application/json",
    "X-RapidAPI-Key": "947b07b162msh3937a2ce72f2e35p107855jsn1c82579ebb36",
    "X-RapidAPI-Host": "student-result-api.p.rapidapi.com",
  },
  data: {
    fetch_uuid: "df80b9e7-cf2c-4e6e-80cf-1db72129dc65",
    studentInfo: [
      {
        matriculationNumber: "140001",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140002",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140003",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140004",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140005",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140006",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140007",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140008",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140009",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140010",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140021",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140022",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140023",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140024",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140025",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140026",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140027",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140028",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140029",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140030",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140031",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140032",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140033",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140034",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140035",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140036",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140037",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140038",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140039",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
      {
        matriculationNumber: "140040",
        level: "200",
        name: "george precious",
        session: "2013/14",
        faculty: "engineering",
        department: "computer engineering",
      },
    ],
  },
};

try {
  const response = await axios.request(options);
  console.log(response.data);
} catch (error) {
  console.error(error);
}
